Content:
  - ${ROOT_DIR}/doc/content
  - ${MOOSE_DIR}/framework/doc/content
  - ${MOOSE_DIR}/modules/heat_transfer/doc/content
  - ${MOOSE_DIR}/modules/ray_tracing/doc/content
  - ${MOOSE_DIR}/modules/solid_mechanics/doc/content
  - ${MOOSE_DIR}/modules/phase_field/doc/content

Renderer:
  type:                            MooseDocs.base.MaterializeRenderer
  favicon:                         media/raccoon_icon.png

Extensions:
  MooseDocs.extensions.navigation:
    name:                          "RACCOON"
    repo:                          https://github.com/hugary1995/raccoon
    google-cse:                    008852834041008754713:g3ilnhhbbj9
    breadcrumbs:                   False
    scrollspy:                     False
    menu:                          !include ${ROOT_DIR}/doc/menu.yml
  MooseDocs.extensions.bibtex:
    duplicates:
      - kim_phase-field_1999 # referenced in both Solid Mechanics and Phase Field
      - hales15homogenization # referenced in both Solid Mechanics and Heat Conduction
  MooseDocs.extensions.katex:
    macros:                        !include ${ROOT_DIR}/doc/katex.macros.yml
  MooseDocs.extensions.appsyntax:
    executable:                    ${ROOT_DIR}
    remove:
      framework:                   !include ${MOOSE_DIR}/framework/doc/remove.yml
  MooseDocs.extensions.common:
    shortcuts:                     !include ${MOOSE_DIR}/framework/doc/globals.yml
  MooseDocs.extensions.acronym:
    acronyms:                      !include ${MOOSE_DIR}/framework/doc/acronyms.yml
  MooseDocs.extensions.template:
    active:                        True
  MooseDocs.extensions.sqa:
    active:                        False
